export const TITLE = "Edita el registro de Proovedores";
export const NAME_SUPPLIER = "Nombre Proovedor";
export const NIT_RUT = "NIT o RUT";
export const EMAIL = "Correo Electronico";
export const NUMBER_PHONE = "Telefono";
export const ADDRESS = "Direccion";
export const CITY = "Ciudad";
export const FAIL = "CANCELAR";
export const DONE = "GUARDAR";