export const TITLE = "Editar el registro de Proveedores";
export const NAME_SUPPLIER = "Nombre del Proveedor";
export const NIT_RUT = "NIT o RUT";
export const EMAIL = "Correo Electrónico";
export const NUMBER_PHONE = "Teléfono";
export const ADDRESS = "Dirección";
export const CITY = "Ciudad";
export const FAIL = "CANCELAR";
export const DONE = "GUARDAR";